DROP TABLE IF EXISTS endpoints_hits;

CREATE TABLE IF NOT EXISTS endpoints_hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR,
    uri       VARCHAR,
    ip        VARCHAR,
    timestamp TIMESTAMP WITHOUT TIME ZONE
);